### ISSUE TITLE
Update/Create doesn't work when on form present Select for relation field

### ISSUE THREAD

**Issue by DriveSoft** [premieroctet/next-admin#113]
I'm using MySQL.  After update (3.2.0) update/create doesn't work when on form present Select input for related field

It's works only if I remove "class" field from edit.display array

When I'm editing a record and didn't choose any value in Select input ("class" field), I'm getting error:

`Invalid `prisma.timetable.update()` invocation: { where: { id: "clradekj60001uyo099jqa6vw" }, data: { start: "2024-01-08T07:00:00.000Z", end: "2024-01-08T08:30:00.000Z", class: { disconnect: true, ~~~~~~~~~~ ? create?: ClassCreateWithoutTimetableInput | ClassUncheckedCreateWithoutTimetableInput, ? connectOrCreate?: ClassCreateOrConnectWithoutTimetableInput, ? upsert?: ClassUpsertWithoutTimetableInput, ? connect?: ClassWhereUniqueInput, ? update?: ClassUpdateToOneWithWhereWithoutTimetableInput | ClassUpdateWithoutTimetableInput | ClassUncheckedUpdateWithoutTimetableInput } } } Unknown argument `disconnect`. Did you mean `connect`? Available options are marked with ?.`

If I chose some value in Select input and try to save record, I'm getting another error:

```
Unhandled Runtime Error
Error: Unexpected token 'c', "cvb9xc7v8b" is not valid JSON

 ⨯ node_modules\@premieroctet\next-admin\dist\utils\server.js (292:56) @ parse
 ⨯ SyntaxError: Unexpected token 'c', "cvb9xc7v8b" is not valid JSON
```

options,tsx:
```
   model: {
      Timetable: { 
         list: {
            display: ["start", "end", "class"],
            fields: {                
               "class": {
                  formatter: (classObj) => {
                     return <strong>{classObj.name}</strong>;
                  },                  
               }             
            }
         },
         edit: {
            display: ["id", "start", "end", "class"]
         }
      },
   },
```

prisma
```
model Timetable {
    id      String   @id @default(cuid())
    start   DateTime
    end     DateTime
    note    String?
    classId String
    class   Class    @relation(fields: [classId], references: [id], onDelete: Cascade)

    @@index([classId], name: "idx_classId")
}

model Class {
    id              String        @id @default(cuid())
    name            String
    schoolAddreesId String
    schoolAddress   SchoolAddress @relation(fields: [schoolAddreesId], references: [id])
    Timetable       Timetable[]
    User            User[]

    @@index([schoolAddreesId], name: "idx_class_schoolAddressId")
}
```

**Comment by tlenclos** [comment]
Hello @DriveSoft ! I think it might be an issue with the reserved keyword `class` in JavaScript/TypeScript.
I strongly advise you to use a naming like `ClassRoom` for your model/table name.

We will keep this issue open to investigate more on the subject.

**Comment by DriveSoft** [comment]
> Hello @DriveSoft ! I think it might be an issue with the reserved keyword `class` in JavaScript/TypeScript. I strongly advise you to use a naming like `ClassRoom` for your model/table name to avoid weird behavior in the codebase.
> 
> We will keep this issue open to investigate more on the subject.

I have checked it, unfortunately in this case it has nothing to do with reserved keyword "class"

**Comment by DriveSoft** [comment]
Thanks, now it works.
