### ISSUE TITLE
Why Search input shows when the property [model-name].list.search does not exists in options file?

### ISSUE THREAD

**Issue by DriveSoft** [premieroctet/next-admin#116]
Why Search input shows when the property [model-name].list.search does not exists in options file?

**Comment by colin27091** [comment]
By default, and to maintain turnkey behavior, the list page search is applied to every scalar field in the model. Currently, the `[model-name].list.search` option is only used for more specific searches. Perhaps in the future we should, hide this search field if `[model-name].list.search = []`

**Comment by colin27091** [comment]
Fix available on [v3.2.2](https://www.npmjs.com/package/@premieroctet/next-admin/v/3.2.2)  🚀
Now you can set an empty array to hide search field on list page
I close this issue, feel free to give feedback
