### ISSUE TITLE
Can't create a record if optional Select field (related) is empty

### ISSUE THREAD

**Issue by DriveSoft** [premieroctet/next-admin#119]
Can't create a record if optional Select field (related) on a form is empty.
I'm getting error:
`Invalid `prisma.school.create()` invocation: { data: { name: "test name", info: "test info", slug: "test-slug", ownerUser: false ~~~~~ } } Argument `ownerUser`: Invalid value provided. Expected UserCreateNestedOneWithoutSchoolInput, provided Boolean.`

At the same time I can update a record when Select field is empty.

**Comment by colin27091** [comment]
Fix available on [v3.2.2](https://www.npmjs.com/package/@premieroctet/next-admin/v/3.2.2)  🚀
I close this issue, feel free to give feedback
