### ISSUE TITLE
A table can't show Decimal fields

### ISSUE THREAD

**Issue by DriveSoft** [premieroctet/next-admin#128]
A table can't show Decimal fields (latitude, longitude) - MySQL
I'm getting warning in console:

```
Warning: Only plain objects can be passed to Client Components from Server Components. Decimal objects are not supported.
  {id: ..., name: ..., country: ..., latitude: Decimal}
```

Model:
```
model City {
    id        Int     @id @default(autoincrement())
    name      String
    latitude  Decimal @db.Decimal(10, 8)
    longitude Decimal @db.Decimal(10, 8)
    countryId Int
    country   Country @relation(fields: [countryId], references: [id])
}
```

**Comment by cregourd** [comment]
This warning is fix in [v3.2.3](https://www.npmjs.com/package/@premieroctet/next-admin/v/3.2.3) 🚀
Feel free to give feedback

**Comment by DriveSoft** [comment]
Unfortunately the new version didn't fix this bug. Decimals fields are still not showing up in a table.

**Comment by cregourd** [comment]
Thanks for your feedback, the fix was indeed the form indeed, we forgot the table part. 
Everything is done in [v3.2.4](https://www.npmjs.com/package/@premieroctet/next-admin/v/3.2.4) 🚀
I close this issue, feel free to reopen it if you faced a problem.
