### ISSUE TITLE
Button on form: [Save and add another]  [Save and continue editing]  [Save]

### ISSUE THREAD

**Issue by DriveSoft** [premieroctet/next-admin#145]
Can you consider to change the submit button on a form?

[Delete]                   [Save and add another]  [Save and continue editing]  [Save]

To make it like in Django admin panel:
![image](https://github.com/premieroctet/next-admin/assets/11293522/fc972c12-9470-4b3a-818e-24af35a8b8f6)

**Comment by cregourd** [comment]
We will take care of this issue, however, we will just add the `Save and continue editing` for now. This feature is currently a `to review` feature

**Comment by cregourd** [comment]
This is available on [v3.2.6](https://www.npmjs.com/package/@premieroctet/next-admin/v/3.2.6) 🚀
Feel free to give feedback
