### ISSUE TITLE
Search UUID fields

### ISSUE THREAD

**Issue by marcoslund** [premieroctet/next-admin#152]
Hi, first of all thank you for all the work you've put into this.

I'm having trouble with the search bar since some of the fields I have are UUIDs in a Postgres database and the `contains` keyword is incompatible with that native type. Is there a way to be able to search through these fields so far? I'm using the latest version 3.2.6.

```
Invalid `prisma.user.findMany()` invocation:

{
  select: undefined,
  where: {
    OR: [
      {
        id: {
          contains: "A",
          mode: "insensitive"
        }
      },
      {
        externalUserId: {
          contains: "A",
          mode: "insensitive"
        }
      },
      {
        personId: {
          contains: "A",
          mode: "insensitive"
        }
      }
    ]
  },
  orderBy: {},
  skip: 0,
  take: 10
}

Unknown argument `contains`. Available options are marked with ?.
```

<img width="1431" alt="image" src="https://github.com/premieroctet/next-admin/assets/29240378/3b6295cd-d1ba-411e-a257-dbd7e6955936">

This is what my Prisma schema looks like:

```
model User {
  id        String     @id @default(uuid()) @db.Uuid
  status    UserStatus @default(CREATED)
  externalUserId String     @unique @map("external_user_id")
  personId  String     @map("person_id") @db.Uuid
  createdAt DateTime   @default(now()) @map("created_at") @db.Timestamptz
  updatedAt DateTime   @updatedAt @map("updated_at") @db.Timestamptz

  person              Person                      @relation(fields: [personId], references: [id])
 
  @@map("user")
}
```

And this is the table definition:

```
CREATE TABLE "user" (
    "id" UUID NOT NULL,
    "status" "user_status_enum" NOT NULL DEFAULT 'active',
    "external_user_id" TEXT NOT NULL,
    "person_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "user_pkey" PRIMARY KEY ("id")
);
```

Also, if I specify which fields to search through (i.e. `name`) I get console logs of SQL queries containing a `WHERE 1=0` clause with no results. Any idea what could be the source of this problem?

```
model: {
    User: {
      list: {
        display: ["id", "status", "externalUserId", "personId", "createdAt", "updatedAt"],
        search: ["status"],
      },
      edit: {
        display: ['id', 'status', 'personId', 'createdAt'],
      },
    },
}
```

```
> prisma:query SELECT "public"."user"."id", "public"."user"."status"::text, "public"."user"."external_user_id", "public"."user"."person_id", "public"."user"."created_at", "public"."user"."updated_at" FROM "public"."user" WHERE 1=0 ORDER BY "public"."user"."id" ASC LIMIT $1 OFFSET $2
> prisma:query SELECT COUNT(*) FROM (SELECT "public"."user"."id" FROM "public"."user" WHERE 1=0 OFFSET $1) AS "sub"
```

<img width="1431" alt="image" src="https://github.com/premieroctet/next-admin/assets/29240378/aed83e7e-e60e-4bc5-b0be-580285f7187a">

Thank you very much.

**Comment by cregourd** [comment]
Hi @marcoslund,

As you said, PostgreSQL does not implement contains search on UUID native type. The only way, but computing expensive, is to cast UUID to TEXT type  during the SQL query. Prisma does not allow this, and we do not want to  bypass Prisma system to make custom query which will be hard to handle according to generics cases de next-admin. 

However, you have two options to make it work based on your needs: 

- If you want to search on this UUID field, even with this constraint: you have to not use native type `uuid` but keep text type by removing `@db.Uuid` in your schema.

- If you just want to not block search on other fields and ignore search on UUID, you have to (as you tried) limit searched fields by setting search options in your config. 

Now for the issue you faced by setting only `status` in the search options, we need more context on your case, especially about `UserStatus`, we assume this is an enum and indeed, according to your statement, it seems there is an issue with searching over enum fields. 

We will work on this second point, but we will also try to ignore the native type UUID in the search to make it work without configuration.
