### ISSUE TITLE
Uploaded image does not show on input element

### ISSUE THREAD

**Issue by DriveSoft** [premieroctet/next-admin#154]
I have an input element to upload a image (AWS S3), but for some reason the uploaded image doesn't show on a form on server, but showing on local machine.

On the server I see just 
![image](https://github.com/premieroctet/next-admin/assets/11293522/b5024624-1848-4e51-83f0-cfc6217d6e3e)

At the same time svg icon has a correct link to uploaded image, but why I see svg icon instead of the uploaded image?

Link to dev server:
https://wdz-five.vercel.app/admin/user/clrt0nqmo00019ue41vzy4qos

**Comment by foyarash** [comment]
Fixed in [v3.3.0](https://github.com/premieroctet/next-admin/releases/tag/%40premieroctet%2Fnext-admin%403.3.0)
