### ISSUE TITLE
Sorting in Table View Breaks with Aliases Added to Model Fields

### ISSUE THREAD

**Issue by cquintini** [premieroctet/next-admin#155]
When aliases are added to any field within the model, the sorting functionality in the table view becomes compromised. This issue arises specifically when attempting to sort data either in ascending or descending order.

I've successfully addressed this problem within my local environment by implementing a patch. To ensure the resolution is properly reviewed and integrated, I've submitted a pull request for your assessment.

Please review the changes and consider merging them into the main branch to rectify this sorting inconsistency.

**Comment by cregourd** [comment]
Hi @cquintini,

First of all, thanks for your pull request.
It's an interesting approach, but we prefer to use the client-side approach in the `List` component to reduce complexity.

You are the first one to make a pull request outside of us, thanks for that. And of course, feel free to make more  🙌

**Comment by cregourd** [comment]
This bug was fix on [v3.2.7](https://github.com/premieroctet/next-admin/blob/%40premieroctet/next-admin%403.2.7/packages/next-admin/CHANGELOG.md#327) 🚀

Feel free to give feedback
