### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'reduce')

### ISSUE THREAD

**Issue by zbeyens** [premieroctet/next-admin#157]
I got to install next `14.1.1-canary` to fix a bug introduced in `14.1.0`, but this led into breaking this package with this error `TypeError: Cannot read properties of undefined (reading 'reduce')` in `getPropsFromParams`.

**Comment by cregourd** [comment]
This bug was fix on [v3.2.7](https://github.com/premieroctet/next-admin/blob/%40premieroctet/next-admin%403.2.7/packages/next-admin/CHANGELOG.md#327) 🚀

Feel free to give feedback
