### ISSUE TITLE
Tailwind conflict

### ISSUE THREAD

**Issue by zbeyens** [premieroctet/next-admin#158]
Since tailwind is used in this package, it's conflicting with consumer's tailwind config, especially the preflight when not used.

There are a few solutions to this:

- use [tailwind prefix](https://tailwindcss.com/docs/configuration#prefix)
- don't use preflight or https://github.com/tailwindlabs/tailwindcss/discussions/7436#discussioncomment-6766649

**Comment by zbeyens** [comment]
next-admin's preflight is overriding my app's preflight defined in `globals.css` imported in the root layout, which starts with 

```css
@import './preflight.css';
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
```

Note that it happens only when loading first the react-admin page. Navigating from another page (without react-admin) to the react-admin page does not trigger that issue.

**Comment by cregourd** [comment]
To isolate Tailwind configurations, maybe you should add [`@config`](https://tailwindcss.com/docs/functions-and-directives#config) pointing to your Tailwind configuration. This is the tag we used in our projects.

If that doesn't change anything, we will go deeper to find a way to isolate the Tailwind configuration of the package

**Comment by zbeyens** [comment]
Thanks for the tip. I've tried this but it does not prevent react-admin's preflight to be applied on the whole app. For example, in my app I have:

```cs
button {
  background-color: transparent; /* 2 */
}

button,
[type='button'],
[type='reset'],
[type='submit'] {
  -webkit-appearance: button; /* 1 */
  /*background-color: transparent; !* 2 *!*/
  background-image: none; /* 2 */
}
```

which is overridden by 

```css
button,
[type='button'],
[type='reset'],
[type='submit'] {
  -webkit-appearance: button;
  background-color: transparent;
  background-image: none;
}
