### ISSUE TITLE
Error: "next/font" requires SWC although Babel is being used due to a custom babel config being present.

### ISSUE THREAD

**Issue by DriveSoft** [premieroctet/next-admin#176]
Hi.

After updating (3.3.1) and installing 
babel-plugin-superjson-next superjson
next-superjson-plugin
and creating .babelrc file

I'm getting messages:
```
Syntax error: "next/font" requires SWC although Babel is being used due to a custom babel config being present.
```

Solution:
if you want to use SWC despite the presence of a .babelrc file you can force it in your next.config.js file.
https://nextjs.org/docs/messages/swc-disabled

```
module.exports = {
  experimental: {
    forceSwcTransforms: true,
  },
}
```

**Comment by foyarash** [comment]
You can also not use babel and simply use `next-superjson-plugin` which is a SWC plugin. With this you can remove the babel plugin and the babelrc file, which should make your error disappear.

Thanks for the feedback !

**Comment by foyarash** [comment]
Closing from inactivity, but feel free to open again if the issue persists
