### ISSUE TITLE
Add external link page

### ISSUE THREAD

**Issue by shinework** [premieroctet/next-admin#190]
Allow user to add external page in the sidebar (absolute URL like `https://www.google.com/`) in https://github.com/premieroctet/next-admin/blob/main/apps/example/options.tsx#L150C3-L150C8

**Comment by foyarash** [comment]
Released in [3.5.0](https://github.com/premieroctet/next-admin/releases/tag/%40premieroctet%2Fnext-admin%403.5.0)
