### ISSUE TITLE
Add indication of the the form being submitted on an edit page

### ISSUE THREAD

**Issue by Vaviloff** [premieroctet/next-admin#206]
Great project, love the simplicity and flexibility!

A small suggestion: for some scenarios where it takes a bit more time to save data (say, making some calculation on save) there wold be nice to have a visual indication that the form has been submitted and is being processed. 

Maybe "Save" button could be disabled and/or spinner could be shown besides or inside of it, that kind of thing.

**Comment by foyarash** [comment]
Released in [v3.6.0](https://github.com/premieroctet/next-admin/releases/tag/%40premieroctet%2Fnext-admin%403.6.0)
