### ISSUE TITLE
After 3.6.0 all Select components on a form are empty

### ISSUE THREAD

**Issue by DriveSoft** [premieroctet/next-admin#210]
I have updated to 3.6.0 and now all Select components does not work, when I'm trying to create a new record, all Select components on a form are empty. When I'm opening an existed record, I see current value in Select component, but can't choose a new value. I have checked network tab on Chrome, and there is no additional request from a Select component to fetch data.

![image](https://github.com/premieroctet/next-admin/assets/11293522/16d469b4-4504-4dcd-9d03-f0bf23aaf193)

**Comment by cregourd** [comment]
Hello @DriveSoft 

Don't you have even a first load when search input is empty ?

**Comment by cregourd** [comment]
Hey @DriveSoft 

Have you added the `searchPaginatedResourceAction` action to the `getPropsFromParams` function?

https://next-admin.js.org/docs/api-docs#functions

**Comment by DriveSoft** [comment]
Hi.

You are right, my bad. Thanks for a great library! :)
