### ISSUE TITLE
Integration with nextui?

### ISSUE THREAD

**Issue by 18601673727** [premieroctet/next-admin#212]
It might be a loss for next-ui not integrated by default and it looks awful after integrated next-admin with my current shadcn settings(`cssVariables: true`):
![火狐截图_2024-03-29T18-54-06 675Z](https://github.com/premieroctet/next-admin/assets/3302620/ed046579-5a06-45ef-8ec4-a48b878b578b)

**Comment by foyarash** [comment]
In a more general way, dark mode is currently not implemented, but should be easily done, thanks for the report

**Comment by foyarash** [comment]
I suppose you are using your own Tailwind CSS file, right ?

Can you add the following to your Tailwind CSS file ?

```css
@layer base {
  body {
    @apply bg-slate-50/50;
  }
}
```

**Comment by 18601673727** [comment]
Yes, shadcn comes with tailwind and my layout.tsx looks like this:
```
<body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
```
Notice that `.bg-background` is added to `<body>` caused the background to black which is following the convention from "https://ui.shadcn.com" offical site, so if I'm being lazy enough to not creating an dedicated Layout for my `/admin/*` then the result depicted in top screenshot would be made.

Anyway, all these trivial details can be solved easily many ways but my point is not about how to make current integration smooth or ergonomically, but to suggest that it would be a good idea to have `next-ui` implemented by default, since you share the most common concepts and for `<Chart>` parts we can let the user to decide which to choose later on individually right?

**Comment by foyarash** [comment]
Hello @18601673727 

[v4.0.0](https://github.com/premieroctet/next-admin/releases/tag/%40premieroctet%2Fnext-admin%404.0.0) has been released with few changes [to the theming](https://next-admin.js.org/docs/theming), aswell with dark mode support.

We hope this will fit your needs

**Comment by 18601673727** [comment]
Thank you, this version works much better, my appreciations!
