### ISSUE TITLE
Relationship select is empty

### ISSUE THREAD

**Issue by thiagosantos25** [premieroctet/next-admin#215]
I have a one-to-many relationship (partner) and two partners already saved to the DB, but the select box never loads any of them:

<img width="338" alt="Screenshot 2024-04-04 at 10 19 30" src="https://github.com/premieroctet/next-admin/assets/137558653/2f586c9e-cae7-4265-afe9-62d8dbafbec9">

I've reviewed my schema and everything looks fine, one thing that crossed my mind is that I'm using MySQL, could that be the reason?

**Comment by cregourd** [comment]
Hey,

Maybe you're facing the same config issue as #210 by forgetting the `searchPaginatedResourceAction` action

**Comment by thiagosantos25** [comment]
That was it, thanks!
