### ISSUE TITLE
Better label field name by default

### ISSUE THREAD

**Issue by shinework** [premieroctet/next-admin#218]
We can refine labels of fields by replacing _ by space : 

![image](https://github.com/premieroctet/next-admin/assets/1102595/69985f08-c299-46d3-9b31-3200fde1fcfa)

**Comment by foyarash** [comment]
Fixed in [v3.6.1](https://github.com/premieroctet/next-admin/releases/tag/%40premieroctet%2Fnext-admin%403.6.1)
