### ISSUE TITLE
"1-N" Relations field display improvements

### ISSUE THREAD

**Issue by tlenclos** [premieroctet/next-admin#219]
## Context
Currently if we have relation between entities, we display a select with ids.
![image](https://github.com/premieroctet/next-admin/assets/686101/3cd22b85-3291-42e6-9ec7-c239bbf86912)

It is a nice default but sometimes we just want to display informations about the relation in a better way.

## TODO
- [ ] add a display type `list` parameter on the relation field to display a simple `<ul><li>...` list
- [ ] add a display type `admin-list` parameter on the relation field to display a table, only available if the entity is already configured in the next-admin configuration

**Comment by ogoldberg** [comment]
On a similar note, for the edit view I've been asked to offer radio buttons for enums. I could understand this being lower priority though for sure since working functionality is in place and this is more of an aesthetic thing

**Comment by foyarash** [comment]
Added in [v4.1.0](https://github.com/premieroctet/next-admin/releases/tag/%40premieroctet%2Fnext-admin%404.1.0)
