### ISSUE TITLE
Add option to choose what user can do at model level (Create, Update, Delete)

### ISSUE THREAD

**Issue by DriveSoft** [premieroctet/next-admin#222]
Hi.

How about to introduce a new option at model level to choose, what action an user can perform (Create, Update, Delete), something like this:

```
   model: {
      User: {
         title: "Users",  
         perms: ["create", "update", "delete"] 
         ...
      }
   }
```
      

If "perms" is not present, an user has all permissions.
In my case I want to prevent deleting users, instead I want to use boolean field to disable an user on my system (soft delete).

**Comment by foyarash** [comment]
Added in [v4.1.0](https://github.com/premieroctet/next-admin/releases/tag/%40premieroctet%2Fnext-admin%404.1.0)
