### ISSUE TITLE
`deleteAction` and `searchPaginatedResourceAction` Examples would be really useful

### ISSUE THREAD

**Issue by ogoldberg** [premieroctet/next-admin#232]
Given that these features are suddenly raising errors, and especially given that `searchPaginatedResourceAction` "just worked" in the previous version, it would be super helpful to see some examples of what these are supposed to look like. I'm trying to add them my setup and I'm struggling to figure out how to implement them, which now means my entire next-admin implementation has completely broken. 

Any way to get some support on this? Thanks!

**Comment by foyarash** [comment]
You can find both of those actions implemented in the example app

https://github.com/premieroctet/next-admin/blob/main/apps/example/actions/nextadmin.ts#L28
