### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by ogoldberg** [premieroctet/next-admin#233]
I really appreciate how great you have been with feedback!
With the new release I'm really struggling with some design issues.
The side panel with all the different models has disappeared and the edit view has gotten a lot messier.
I know you said something in the changelog about styles, but I don't really know how to figure out how to get things looking good again. 

I'd love to even just match what you've got in the demo, but I'm having a hard time understanding your implementation.
I'm not terribly worried about having it in some particular way, but I do want to have the side panel back, and I need the edit form to be comprehensible. 

Is there a way you can give back a nice default style that works well out of the box? I really loved that about this project.

**Comment by foyarash** [comment]
Hello @ogoldberg did you manage to make it work ?

v4 introduced a breaking change that requires you to setup Tailwind on your side, you can check [the docs](https://next-admin.js.org/docs/getting-started) for more info

**Comment by ogoldberg** [comment]
Honestly, I made it work by reverting to the previous version. I was already using tailwind so I felt like a fish out of water and not sure what the path forward was. Maybe once you have a chance to update the example that will help.

**Comment by foyarash** [comment]
Example is up to date ! :)

You now have to use the preset https://github.com/premieroctet/next-admin/blob/main/apps/example/tailwind.config.js#L149

And also make sure to include the lib's files in the content `https://github.com/premieroctet/next-admin/blob/main/apps/example/tailwind.config.js#L10`

**Comment by ogoldberg** [comment]
@foyarash Thanks for updating.
Unfortunately, even when I update my tailwind.config.js file with those lines, I still am missing the nvaigation sidebar and getting awkward styling on the form view.

**Comment by foyarash** [comment]
Have you imported your css file like done [here](https://github.com/premieroctet/next-admin/blob/main/apps/example/app/%5Blocale%5D/layout.tsx#L2) ? (it can be in your page aswell)

**Comment by ogoldberg** [comment]
yeah, well, my layout is importing my global styles, yes. And I am using tailwind. But I am not writing my own styles specifically for next-admin. And the list view I see is not ugly or styled badly. But I don't see the sidebar to navigate between models, and the edit form has a lot to be desired.

I just really like the way it worked before and it no longer looks the same.

**Comment by foyarash** [comment]
Could you share your tailwind config file please ?

**Comment by ogoldberg** [comment]
```
import type { Config } from 'tailwindcss';
const config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      fontFamily: {
        secondary: 'Protest Strike',
        // sans: [font.className],
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        slate: {
          DEFAULT: 'hsl(var(--slate))',
          100: 'hsl(var(--slate-100))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          100: 'hsl(var(--primary-100))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;

export default config;

```

**Comment by foyarash** [comment]
I can see there is no preset and required content here, is that the one you used in v4 ?

**Comment by ogoldberg** [comment]
yes. Forgive me, I'm not familiar with what you mean. Can you help me understand what I need to do?

**Comment by ogoldberg** [comment]
I figured this out. Thanks for your guidance! I appreciate all your hard work on this library, and all your help!
