### ISSUE TITLE
`styles.css` does not exist

### ISSUE THREAD

**Issue by nahtnam** [premieroctet/next-admin#234]
`import "@premieroctet/next-admin/dist/styles.css";` is in the docs but the file does not exist in `4.0.0`

**Comment by foyarash** [comment]
Hello @nahtnam thanks for your feedback we forgot to update the samples provided in the README and Getting Started, we will update those.

For your information, you now have to setup Tailwind in your app, as stated [in the docs](https://next-admin.js.org/docs/getting-started)

**Comment by foyarash** [comment]
Doc has been updated, thanks for the report
