### ISSUE TITLE
SSR Issue

### ISSUE THREAD

**Issue by nahtnam** [premieroctet/next-admin#235]
<img width="1016" alt="image" src="https://github.com/premieroctet/next-admin/assets/20051852/8f3516e5-853f-4af7-8d08-06defbe1b246">

I'm getting the following error when rendering the NextAdmin component

**Comment by foyarash** [comment]
Hello

Thanks for the report. Are you seeing this on page router or app router ?

**Comment by ogoldberg** [comment]
I'm not the OP, but I see this using App router

**Comment by foyarash** [comment]
Hello

I was able to reproduce the issue. This seems to happen when you have a single root layout file, but multiple layout files producing an `html` tag with its `body`. A workaround is to [create multiple root layout](https://nextjs.org/docs/app/building-your-application/routing/route-groups#creating-multiple-root-layouts), one root layout for your app and one for the admin.
