### ISSUE TITLE
edit form relationship selection dropdown: previously selected options still appear as selectable options

### ISSUE THREAD

**Issue by ogoldberg** [premieroctet/next-admin#236]
v3.6.1
In the edit form, when interacting with a relationship field, it would be ideal if once an entity has been selected that it would no longer appear in the drop down of available options.

**Comment by foyarash** [comment]
Fixed in [v4.1.0](https://github.com/premieroctet/next-admin/releases/tag/%40premieroctet%2Fnext-admin%404.1.0)
