### ISSUE TITLE
GREAT Project: Suggestion - Headless CMS Application

### ISSUE THREAD

**Issue by kam-st** [premieroctet/next-admin#237]
Great project guys,

I was thinking of creating one myself. But I feel like this can gain significant more traction if it is build as headless cms. Maybe combining power of zenstack? To build admin dashboard that allows RBAC and stripe integration. More in line with payload cms?

**Comment by cregourd** [comment]
The initial project involved building a turnkey administration system close to the application. This avoided deploying the administration on another domain. I think we're more likely to talk about a coupled CMS. That's the main advantage of this solution. You can also use an RBAC directly in your Next.js application.

But it would be nice to see a headless variant, thanks for your interest. 🚀
