### ISSUE TITLE
[BUG] - Unable to sort on relationship columns in list view

### ISSUE THREAD

**Issue by ogoldberg** [premieroctet/next-admin#248]
### Description

If I click on attribute headers of a model in list view it will sort properly, but if I click on the header of a column that represents a relationship, it does not sort.

### Reproduction URL

https://no-url.com

### Reproduction steps

```bash
1. Go to a list view
2. Click on the header for a relationship attribute
3. It does not sort.
```

### Next router

App router

### Next Admin version

4.0.0

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

**Comment by foyarash** [comment]
Fixed in [v4.1.0](https://github.com/premieroctet/next-admin/releases/tag/%40premieroctet%2Fnext-admin%404.1.0)
