### ISSUE TITLE
[BUG] - unexpected `formatter` behavior

### ISSUE THREAD

**Issue by ogoldberg** [premieroctet/next-admin#249]
### Description

I have a field called `published`
in my list section it looks like this:
```
 fields: {
              published: {
                formatter: (value: boolean) => {
                  return value ? 'Published' : 'Unpublished';
                },
              },
```
The strange behavior is that if it is true it displays "Published", but if it is false, it displays "false" and it never displays "Unpublished".
I can't wrap my head around it.

### Reproduction URL

https://no-url.com

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Next router

App router

### Next Admin version

4.0.0

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

**Comment by foyarash** [comment]
Fixed in [v4.1.0](https://github.com/premieroctet/next-admin/releases/tag/%40premieroctet%2Fnext-admin%404.1.0)
