### ISSUE TITLE
[FEATURE] - search by relationship attributes

### ISSUE THREAD

**Issue by ogoldberg** [premieroctet/next-admin#250]
### Summary

I have a Job model, and it has a relationship with the Employer model.
The list view of the Job model displays the Employer name, but the search does not filter by the employer name.
I would love it if I could search by the relationship field that is on display in the list view

### Basic Example

I have a Job model, and it has a relationship with the Employer model.
The list view of the Job model displays the Employer name, but the search does not filter by the employer name.
I would love it if I could search by the relationship field that is on display in the list view

### Drawbacks

I understand that the implementation here is not very straightforward, but if I could configure the searchable fields to include attributes on relationship fields that would be pretty great. not sure if it would be dot notation or an object, but since we are assuming prisma, I think it's doable.

### Unresolved questions

I suppose it's possible that this will require a bit of a refactor of the search behavior, but I don't really know.

**Comment by foyarash** [comment]
Hello @ogoldberg , we are currently working on a filter feature, that would also involve filtering by relationship.

**Comment by ogoldberg** [comment]
Hooray! Thank you
