### ISSUE TITLE
[FEATURE] - Add required field option for many-to-many relationships or in general for fields that are not required

### ISSUE THREAD

**Issue by ogoldberg** [premieroctet/next-admin#257]
### Summary

I love that next-admin leverages the prisma schema to determine required vs not-required fields, but it would be really cool to be able to override the schema for the sake of these forms, at least to make something required that the schema doesn't require.

For instance, in prisma there's no way (that I'm aware of) to specify that a many to many relationship is required. I understand why this is complicated, but I'm wondering if we can add a way to mark a field as required even when the schema says otherwise.

### Basic Example

In my example, I have a job model and an industries model. A job can have many industries, and an industry can have many jobs.

In my prisma schema I don't have a question mark on this relationship, but yet I can create a job without associating any industries.

I would like to be able to add a `required: true` to the field in my next-admin options and have the field be required.

### Drawbacks

there could be some confusion because it will be impossible to say that a field is NOT required when the db requires it.

**Comment by cregourd** [comment]
Hey, this feature is available on [v4.2.0](https://www.npmjs.com/package/@premieroctet/next-admin/v/4.2.0) 🚀
Feel free to give us feedback
