### ISSUE TITLE
[FEATURE] - Customize url and breadcrumbs

### ISSUE THREAD

**Issue by ogoldberg** [premieroctet/next-admin#263]
### Summary

I'd like to have the urls and breadcrumbs be configurable so that they can be set to use any unique field (e.g. `slug`) rather than just the @id field.

### Basic Example

I'd like to have the urls and breadcrumbs be configurable so that they can be set to use any unique field (e.g. `slug`) rather than just the @id field. This will allow for a cleaner look and make urls more human readable.

**Comment by cregourd** [comment]
Hi @ogoldberg,

Thanks for your feedback, we think possibly to custom URL will bring lots of side effect, also we didn't know any example of an admin using custom URL identifier

However, we can use `toString` function defined in options to format breadcrumb identifier if you think this can make sense

**Comment by ogoldberg** [comment]
Fair enough.
The `toString` idea for breadcrumbs would actually be really useful. Thanks!

**Comment by cregourd** [comment]
This feature is available in [v4.2.2](https://www.npmjs.com/package/@premieroctet/next-admin/v/4.2.2)

Feel free to give us feedback 🚀
