### ISSUE TITLE
[DOC] - Recipe to export data

### ISSUE THREAD

**Issue by tlenclos** [premieroctet/next-admin#265]
### Summary

A first implementation was done here https://github.com/premieroctet/next-admin/pull/89 but it was not the same between App & page router, and it wasn't supporting streaming & direct file download.

### Basic Example

We should add a recipe in the documentation and the example app doing 
- streaming response
- content disposition download (click on link forces download in the browser)
- custom secure API endpoint

**Comment by ogoldberg** [comment]
Does this recipe live somewhere? I can't find it

**Comment by ogoldberg** [comment]
Just following up on this again.
I would love to get a recipe for csv export if that's possible. Would be insanely helpful to me at this point.
