### ISSUE TITLE
[FEATURE] - Support Edge runtime

### ISSUE THREAD

**Issue by zbeyens** [premieroctet/next-admin#273]
### Summary

CloudFlare only supports edge runtime, so it would be nice to support it.

Adding `export const runtime = 'edge'` throws this error:

```
./node_modules/.pnpm/@premieroctet+next-admin@4.0.0_@babel+core@7.24.5_@prisma+client@5.13.0_@types+react-dom@18.3_o5vmxd7xi4lgsgrvif33n2qymu/node_modules/@premieroctet/next-admin/dist/hooks/useRouterInternal.js:4:0
Module not found: Can't resolve 'querystring'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/@premieroctet+next-admin@4.0.0_@babel+core@7.24.5_@prisma+client@5.13.0_@types+react-dom@18.3_o5vmxd7xi4lgsgrvif33n2qymu/node_modules/@premieroctet/next-admin/dist/components/Dashboard.js
```

### Basic Example

`export const runtime = 'edge'`

**Comment by zbeyens** [comment]
Hi @cregourd , thanks for the quick help! Here are the errors left in 4.2.1:

```bash
./node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:1:2792
Module not found: Can't resolve 'os'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/@premieroctet+next-admin@4.2.1_@babel+core@7.24.5_@prisma+client@5.13.0_@types+react-dom@18.3_oq2ngw3r5xqc4ixcfbt5wejqye/node_modules/@premieroctet/next-admin/dist/actions/form.js
./node_modules/.pnpm/@premieroctet+next-admin@4.2.1_@babel+core@7.24.5_@prisma+client@5.13.0_@types+react-dom@18.3_oq2ngw3r5xqc4ixcfbt5wejqye/node_modules/@premieroctet/next-admin/dist/actions/index.js
./src/app/(dynamic)/(main)/studio/admin/[[...nextadmin]]/actions.ts
./src/app/(dynamic)/(main)/studio/admin/[[...nextadmin]]/page.tsx
```

As well for `path`, `fs`, `child_process`, `fs/promises`.

It looks like importing from `@prisma/client/runtime/library` is the fault here.

```ts

import {
  PrismaClientKnownRequestError,
  PrismaClientValidationError,
} from "@prisma/client/runtime/library"
```

**Comment by cregourd** [comment]
After a thorough review of `edge` support, I regret to inform you that it is currently not possible to implement it.

Next-admin uses Prisma.DMMF to work, but [Prisma.DMMF is not available on edge runtimes](https://github.com/prisma/prisma/blob/6a831f8826665b8dc10c7f615d5856d543661e61/packages/client/tests/functional/prisma-dot-dmmf/tests.ts#L15) - [issue](https://github.com/prisma/prisma/issues/23913)

The only way to get it to work would be to create a custom Prisma generator to get all the information we need from the model and replace `prisma-json-schema-generator` with it. However, this is not currently a planned task and will be tedious. 

If you have another idea to solve this problem, please let us know. And feel free to submit other alternatives 🙂

**Comment by zbeyens** [comment]
This is indeed a Prisma issue, let's wait they fix it. Thanks again for the quick support.
