### ISSUE TITLE
[FEATURE] - Docs for how to make a PR

### ISSUE THREAD

**Issue by ogoldberg** [premieroctet/next-admin#310]
### Summary

I found a minor typo that I wanted to fix and I want to make a PR, but I'm not sure how you'd like me to go about this. Would be nice to have a doc on what you'd like contributors to do in order to make a successful PR.

### Basic Example

I found a minor typo that I wanted to fix and I want to make a PR, but I'm not sure how you'd like me to go about this. Would be nice to have a doc on what you'd like contributors to do in order to make a successful PR.

**Comment by cregourd** [comment]
Hey there,

There is a [CONTRIBUTING.md](https://github.com/premieroctet/next-admin/blob/main/CONTRIBUTING.md#current-major-release-features) where you can find information about the workflow. 
The only thing that is not detailed in that doc is that you have to create a `changeset` file by running the `changeset add` script (we will add it to CONTRIBUTING.md)

**Comment by ogoldberg** [comment]
nice! thanks!
