### ISSUE TITLE
[FEATURE] - Support Array fields Prisma

### ISSUE THREAD

**Issue by cregourd** [premieroctet/next-admin#322]
### Summary

Allow the use of [list type](https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/working-with-scalar-lists-arrays) in the Prisma model. Currently, arrays are used to represent relationships in forms. However, Prisma allows users to create scalar lists.
Find a way to distinguish between relationship arrays and scalar lists.

### Basic Example

Imagine a `Post` which has a `tags` property as a list of strings. This feature allows you to order/add/remove tags for a Post

**Comment by nahtnam** [comment]
Experiencing this with a array of strings

**Comment by FacundoSpira** [comment]
Hey @cregourd,  is there any estimation on when this will be added? Or any way we can help?

It's a pretty common use case to have a scalar list. Then, since we can't even override the input itself, we are forced to create a lot of custom pages

**Comment by foyarash** [comment]
Hello @FacundoSpira I can start having a look next week depending on the time I have, but feel free to open a PR if you want !

**Comment by foyarash** [comment]
Available in v5.3.0
