### ISSUE TITLE
[FEATURE] - Add filter

### ISSUE THREAD

**Issue by cregourd** [premieroctet/next-admin#326]
### Summary

To complement the [`Quick Filter`](https://github.com/premieroctet/next-admin/issues/245). It would be useful to have a complete filtering system.

In this system, we could add filters that are added directly to the search parameters (sharing the URL keeps the filter).

Filters are based on field types

### Basic Example

Perhaps we could imagine a filter on deep data through relationships

### Unresolved questions

What format should these filters be in?

Will these filters be generated based on Prisma type or JSON schema ?

**Comment by foyarash** [comment]
Released in v5.5.0
