### ISSUE TITLE
[BUG] - translations

### ISSUE THREAD

**Issue by BetaTH** [premieroctet/next-admin#333]
### Description

Some translantios are not working and i think that is a build problem
like edit, create and logout

### Reproduction URL

.

### Reproduction steps

in this repository we this at packages > next-admin > src > components > Form.tsx
~~~typescript
  const breadcrumItems = [
    {
      label: t(`model.${resource}.plural`, {}, title),
      href: `${basePath}/${slugify(resource)}`,
      icon,
    },
    {
      label: edit ? t("actions.edit.label") : t("actions.create.label"),
      href: `${basePath}/${slugify(resource)}/${id}`,
      current: !edit,
    },
  ];
~~~
So with `t("actions.edit.label")` it should be dynamic

but when we install the lib we have this at node_modules > @premieroctet > next-admin > dist > components > Form.js

~~~javascript
    const breadcrumItems = [
        { label: title, href: `${basePath}/${slugify(resource)}`, icon },
        {
            label: edit ? `Edit` : "Create",
            href: `${basePath}/${slugify(resource)}/${id}`,
            current: !edit,
        },
    ];
~~~
you can notice that the label of the second item in breadcrumItems are not dynamic so the translation not work for this

*the logout button also can't be translated*

### Next router

App router

### Next Admin version

4.4.0

### Screenshots

repository
![image](https://github.com/premieroctet/next-admin/assets/32848294/a2225958-ffb7-44a4-a9cd-e086f96be283)

lib installed
![image](https://github.com/premieroctet/next-admin/assets/32848294/bae3d2bf-819a-4fd0-824a-0db178d0e76c)

**Comment by cregourd** [comment]
This feature is now available on [v4.4.1](https://www.npmjs.com/package/@premieroctet/next-admin/v/4.4.1) 

Feel free to give us feedback 🚀
