### ISSUE TITLE
[FEATURE] - Add row item in `formatter`

### ISSUE THREAD

**Issue by zbeyens** [premieroctet/next-admin#334]
### Summary

It would be nice to have a way to access the row object from a cell, as it is possible in [TanStack table](https://tanstack.com/table/v8/docs/guide/cells#cell-rendering).

### Basic Example

`formatter: (cell, context, row) => ReactNode`
or `row` could be added to `context`

**Comment by cregourd** [comment]
Thank you for this proposal. This is now available on [v4.4.1](https://www.npmjs.com/package/@premieroctet/next-admin/v/4.4.1)

Feel free to give us feedback 🚀
