### ISSUE TITLE
[BUG] - Missing datetime field on edit view when schema has default value

### ISSUE THREAD

**Issue by ogoldberg** [premieroctet/next-admin#340]
### Description

I have a postgresql database.
I have a field called `applicationDeadline`
It's been working fine without a default value.
I was asked to have it default to 60 days in the future.
I updated my prisma schema like this:
` applicationDeadline   DateTime?             @default(dbgenerated("(NOW() + '60 days'::interval)"))`
and now the field no longer appears in next-admin when creating a new entry
and once the value has been set, it then appears, but is uneditable.

### Reproduction URL

asdf

### Reproduction steps

```bash
1. Go to your schema
2. Set a field like this 
` applicationDeadline   DateTime?  @default(dbgenerated("(NOW() + '60 days'::interval)"))`
3. Make sure your options indicates this field should appear
4. Field does not appear in admin edit view for new entry
5. Field does appear, but is non-editable for existing value even though I never specified that.
```

### Next router

App router

### Next Admin version

4.4.0

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

**Comment by cregourd** [comment]
This bug was fixed on [v4.4.2](https://www.npmjs.com/package/@premieroctet/next-admin/v/4.4.2) 🚀

Feel free to give us feedback
