### ISSUE TITLE
[FEATURE] - Give Rich Text Field a fixed height with scroll and a draggable corner to adjust size

### ISSUE THREAD

**Issue by ogoldberg** [premieroctet/next-admin#348]
### Summary

Right now if a rich text field has a large body of text, it fills up a lot of space on the view.
It would be preferable if it had a max height by default with a scroll bar, and had a draggable corner so a user can manually expand it if they want.

### Basic Example

see summary

**Comment by cregourd** [comment]
This feature is available on [v4.4.2](https://www.npmjs.com/package/@premieroctet/next-admin/v/4.4.2) 🚀

Feel free to give us feedback

**Comment by ogoldberg** [comment]
> This feature is available on [v4.4.2](https://www.npmjs.com/package/@premieroctet/next-admin/v/4.4.2) 🚀
> 
> Feel free to give us feedback

Thanks @cregourd !
Just one minor issue. The draggable corner is somehow not draggable. 😃
