### ISSUE TITLE
[BUG] - Cannot create when have a foreign model required

### ISSUE THREAD

**Issue by PikPakPik** [premieroctet/next-admin#355]
### Description

When you have a list of foreign keys which is mandatory it is impossible to create on iPad iPhones regardless of the browser

No error is reported or other just the button when you click nothing happens

IOS 18/17, MacOS 15/14 with Safari

### Reproduction URL

no need

### Reproduction steps

```bash
1. Have a model with a foreign key 
OR
1. Go to the demo website and test to create a Post
```

### Next router

App router

### Next Admin version

4.4.2

### Screenshots

![IMG_1966](https://github.com/premieroctet/next-admin/assets/57991630/5ceae426-e1c6-4377-b235-d51c12752114)

### Browsers

Chrome/Safari/Firefox (IOS), Safari (MacOS)

**Comment by cregourd** [comment]
The fix for this issue is available on [v4.4.3](https://next-admin.js.org/changelog#443)

Feel free to give us feedback 🚀
