### ISSUE TITLE
[FEATURE] - Loading animation

### ISSUE THREAD

**Issue by ogoldberg** [premieroctet/next-admin#364]
### Summary

Since some of the views load slowly, it would be nice to have a loading animation like a skeleton or shimmer. I suppose some might want to customize, in which case you could have a really neutral default with the option to customize.

### Basic Example

Since some of the views load slowly, it would be nice to have a loading animation like a skeleton or shimmer.

### Drawbacks

 I suppose some might want to customize, in which case, if this felt important, you could have a stylistically neutral default (like skeleton) with the option to customize.

**Comment by cregourd** [comment]
In [v4.4.5](https://www.npmjs.com/package/@premieroctet/next-admin/v/4.4.5) we've improved the select loader for relationship fields. Data (list | form) is fetched sever-side before rendering. 

Where would you like to implement a skeleton ?

Let us know if the loader is enough, or if you're talking about a deeper enhancement 🚀

**Comment by foyarash** [comment]
Closing as this feature was done.
