### ISSUE TITLE
[BUG] - File component does not show image on a form

### ISSUE THREAD

**Issue by DriveSoft** [premieroctet/next-admin#368]
### Description

I have updated the library from 3.6.0 to 4.4.4
After that I can't see on a form uploaded image.
I checked that handler.get is work, I'm getting url and return full url of the image

![image](https://github.com/premieroctet/next-admin/assets/11293522/851d0ba2-e60b-4de4-85e7-f343281678bc)

options.ts
```
               image: {
                  format: "file",
                  handler: {
                     get: (input: string | null) => {                        
                        return input !== null && input !== "" ? `${env.NEXT_PUBLIC_STORAGE_URL}/${input}` : input;
                     },
                  },
               },
```

### Reproduction URL

none

### Reproduction steps

```bash
1. Open record to see a form
```

### Next router

App router

### Next Admin version

4.4.4

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by cregourd** [comment]
If you are using a storage (e.g. S3) you need to allow your application domain in the CORS policy of your storage. 

This should solve your issue, let us know if this works 🚀

**Comment by DriveSoft** [comment]
Yes, I'm usinng S3 storage.

So now the image is downloaded on server-side? but why?

My CORS config in a bucket has this configuration, it should work:
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD",
            "PUT",
            "POST",
            "DELETE"
        ],
        "AllowedOrigins": [
            "http://localhost:3000",
            "http://127.0.0.1:3000"
        ],
        "ExposeHeaders": []
    }
]
```

**Comment by DriveSoft** [comment]
My bad, turned out there was some issue with cache.
