### ISSUE TITLE
[BUG] - Form does not update explicit many-to-many data

### ISSUE THREAD

**Issue by DriveSoft** [premieroctet/next-admin#373]
### Description

I have faced with a bug, a form does not update **explicit** many-to-many data when I for example add a new item or remove it from the list for already existed record. But at the same time it works fine when I'm creating a new record and add few items in many-to-many list on the form.

### Reproduction URL

none

### Reproduction steps

```bash
1. Open existed record
2. Try to add an item into list which represent many-to-many data for opened record.
3. Click Save button
4. Again open the same record to see, that the list with many-to-many data does not contain latest changes.
```

### Next router

App router

### Next Admin version

4.4.4

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by mahbd** [comment]
I can confirm this issue still exist.

**Comment by mahbd** [comment]
I'm facing the same issue. I'm using Mongodb.

**Comment by foyarash** [comment]
Hello @DriveSoft, could you please update to v5 and check if the issue still persists ? Thank you
