### ISSUE TITLE
[BUG] - Form does not update JSON input value after react-hydration-error

### ISSUE THREAD

**Issue by DriveSoft** [premieroctet/next-admin#376]
### Description

In my options.tsx file I'm showing user name and user email in method toString

```
   model: {
      User: {
         title: "Users",
         toString: (user) => `${user.name} (${user.email})`,
```

But it causes error when I'm opening a form with existed record: 
![image](https://github.com/user-attachments/assets/3114798e-8d86-4840-9233-dfaeeff50f8f)
![image](https://github.com/user-attachments/assets/58b9c944-c595-4a04-bee0-1e99758efc70)

On the form I have JSON input component which does not return updated value anymore after those errors, so basically I'm not be able to update json data for the opened record.

If I just remove user.email from toString methods, everything works fine:
```
   model: {
      User: {
         title: "Users",
         toString: (user) => user.name ?? "",
```

### Reproduction URL

none

### Reproduction steps

```bash
none
```

### Next router

App router

### Next Admin version

4.4.4

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by foyarash** [comment]
Hello @DriveSoft , could you please update to v5 and check if the issue still persists ? Thank you !
