### ISSUE TITLE
[FEATURE] - Add custom actions to the actions column

### ISSUE THREAD

**Issue by eng-ahmad-sameer** [premieroctet/next-admin#387]
### Summary

The custom action can be accessed from the actions dropdown for all selected rows.
It would be good if could be accessed from the actions columns in addition to the delete actions.

### Basic Example

send email existed here in the dropdown actions
![image](https://github.com/user-attachments/assets/28cf4e66-5885-45af-9a81-a4333ec51f5a)

It would be useful if added here too
![image](https://github.com/user-attachments/assets/4b36fdba-6a40-42e4-8c12-7f737fc0ee3a)

### Drawbacks

Can't see any drawback.

**Comment by FacundoSpira** [comment]
Hey @foyarash how are you doing?
Is there any estimation on when this PR, alongside the other open PRs will be merged and released? 
Really looking forward to start testing and using the new features 🚀

**Comment by foyarash** [comment]
Available in v5.3.0
