### ISSUE TITLE
[BUG] - empty list display always the model name not the title

### ISSUE THREAD

**Issue by eng-ahmad-sameer** [premieroctet/next-admin#400]
### Description

![image](https://github.com/user-attachments/assets/385dae4b-8994-4ff6-ac18-8bcc5c075023)

It would be better to provide a way to specify it with a title as a default value.

### Reproduction URL

none

### Reproduction steps

```bash
none
```

### Next router

App router

### Next Admin version

^5.3.0

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

**Comment by foyarash** [comment]
Fixed in v5.3.1
