### ISSUE TITLE
[FEATURE] - Custom generator

### ISSUE THREAD

**Issue by foyarash** [premieroctet/next-admin#414]
### Summary

Currently, generating we are using `prisma-json-schema-generator` to generate a JSON schema that we then have to import and pass into `getNextAdminProps`. This requires an extra dependency installation and an extra import of something that the user should not really care about.

The custom generator would allow us to add `prisma-json-schema-generator` as a dependency of next-admin, and to output the JSON schema directly in the node_modules (for example `node_modules/.next-admin/json-schema.json`). it would also allow us, in the future, to add some more customization to the JSON schema that would make the DMMF obsolete, since we could add all the DMMF information into the JSON schema.

### Basic Example

```prisma
generator nextAdmin {
  provider              = "@premieroctet/next-admin/generator"
}
```

**Comment by FacundoSpira** [comment]
Really like this idea! If the DMMF is eventually deprecated, this can allow in the future to support different ORMs, for example Drizzle 👀

**Comment by milani** [comment]
Is there a plan to support a custom `output`?

**Comment by foyarash** [comment]
Hello @milani , there is no plan to support a custom output as the output we are using in the generator is then used in the library to retrieve the schema. Could you share the reason why you need to custom output ?
