### ISSUE TITLE
[BUG] - Image is missing required "width" property

### ISSUE THREAD

**Issue by zbeyens** [premieroctet/next-admin#420]
### Description

I get this error when using `user.data.picture` prop

### Reproduction URL

none

### Reproduction steps

```bash
<NextAdmin
      {...props}
      user={{
        data: {
          name: currentUser.name!,
          picture: currentUser.profileImageUrl!,
        },
        logout: ['/'],
      }}
    />
```

### Next router

App router

### Next Admin version

6.0.0

### Screenshots

![image](https://github.com/user-attachments/assets/4a839976-1c97-408c-8fe2-909b6c6ed570)

**Comment by cregourd** [comment]
Hello,

Thanks for the issue, we've just fixed it in [v6.0.1](https://www.npmjs.com/package/@premieroctet/next-admin/v/6.0.1)

Feel free to give feedback 🚀
