### ISSUE TITLE
Feedback for “I18n”

### ISSUE THREAD

**Issue by kaluxxx** [premieroctet/next-admin#425]
Hello, 

I've looked in the documentation for a way to translate the success messages after form submission, as well as the global form error message (the one that appears at the top of the form).

Maybe I've done my research wrong, but I don't think that's possible.  Is it possible to do it? 

Thank you for your help

**Comment by cregourd** [comment]
Hello, thanks for your feedback

In fact, there were no translation keys for the messages that appear at the top of the form. It is now possible to translate them using new translation keys: `form.create.succeed`, `form.update.succeed`, `form.delete.succeed`, `form.validation.error`. Use [v6.0.1](https://www.npmjs.com/package/@premieroctet/next-admin/v/6.0.1) to do this 🚀
