### ISSUE TITLE
[FEATURE] - Conditional actions on one record

### ISSUE THREAD

**Issue by nmalzieu** [premieroctet/next-admin#430]
### Summary

Currently we can define actions that get executed for one or multiple records
It would be very helpful to have actions that are only available on one record, and that would appear based on attributes of that record

### Basic Example

For instance: an action to send an email to a user only if a user has a certain status. That action would only appear on users with that specific status.

**Comment by cregourd** [comment]
Hi, thanks for your feedback

We've just added this feature. You can now use the `canExecute` function that gives you access to the current object with a 2-level depth relationship. This function works on any action, anywhere (list action on row, form, multiple choice list). In the case of action on multiple objects, if any object does not satisfy the constraint, the action will be disabled (but still visible) and you can customize a message to explain why this action is disabled. For form and row actions, if the object does not satisfy the constraint, the action will not be visible.

The new [v6.1.0](https://www.npmjs.com/package/@premieroctet/next-admin/v/6.1.0) is available, feel free to give another feedback 🚀

**Comment by nmalzieu** [comment]
> Hi, thanks for your feedback
> 
> We've just added this feature. You can now use the `canExecute` function that gives you access to the current object with a 2-level depth relationship. This function works on any action, anywhere (list action on row, form, multiple choice list). In the case of action on multiple objects, if any object does not satisfy the constraint, the action will be disabled (but still visible) and you can customize a message to explain why this action is disabled. For form and row actions, if the object does not satisfy the constraint, the action will not be visible.
> 
> The new [v6.1.0](https://www.npmjs.com/package/@premieroctet/next-admin/v/6.1.0) is available, feel free to give another feedback 🚀

Same, will test this week and let you know!
