### ISSUE TITLE
[BUG] - action successMessage / errorMessage shown only on resource list, not on resource edit page

### ISSUE THREAD

**Issue by nmalzieu** [premieroctet/next-admin#434]
### Description

If you setup an action

```
actions: [
        {
          id: "action-id",
          title: "Action title",
          action: async (ids) => {
              if (shouldFail) {
                      throw new Error("failing")
              }
          },
          successMessage: "Success",
          errorMessage: "Failed",
        },
      ],
```

the "Success" or "Failed" message appears if you called the action from the resource list page. However it doesn't appear in the UI if you called the action from the edit page.

### Reproduction URL

https://github.com

### Reproduction steps

```bash
1. Go to a resource
2. Click on a row
3. Trigger action
4. See no message displays
```

### Next router

App router

### Next Admin version

6.0.1

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by cregourd** [comment]
Hi, thanks for your feedback

We've just fixed this issue, the new [v6.1.0](https://www.npmjs.com/package/@premieroctet/next-admin/v/6.1.0) is available, feel free to give another feedback 🚀
