### ISSUE TITLE
[FEATURE] - Custom error message / success message for actions

### ISSUE THREAD

**Issue by nmalzieu** [premieroctet/next-admin#435]
### Summary

Right now, `successMessage` /  `errorMessage` is a string that we setup when we define an action. However there can be multiple reasons why an action fails. It would be great to be able to return a custom success / error message from the `action` method itself

### Basic Example

For instance, trying to call a "sendEmail" method on a non paying user could fail with a message "This user is non paying, can't send email"

**Comment by cregourd** [comment]
Hi, thanks for your feedback

We've just added these features, you can now use the previous system to display messages, and a new one based on the return ([MessageData](https://github.com/premieroctet/next-admin/blob/d7ae20c66766a49abe341e1496e9b1289f1b2552/packages/next-admin/src/types.ts#L535-L538)) of the `action` function or thrown error during its execution. Dialog actions can now also display a message on their closing by using a [MessageData](https://github.com/premieroctet/next-admin/blob/d7ae20c66766a49abe341e1496e9b1289f1b2552/packages/next-admin/src/types.ts#L535-L538) object and passing it to the `onClose` function in the component.

The new [v6.1.0](https://www.npmjs.com/package/@premieroctet/next-admin/v/6.1.0) is available, feel free to give another feedback 🚀
