### ISSUE TITLE
[FEATURE] - Text align on rich text

### ISSUE THREAD

**Issue by kaluxxx** [premieroctet/next-admin#437]
### Summary

Hi, I'm working on a project that requires the use of the rich text editor, but I've noticed that the text can't be aligned. 

Could you add the ability to align text left, center or right with the rich text editor buttons. 

See screenshot for example

Thanks in advance

### Basic Example

![image](https://github.com/user-attachments/assets/401e4ebf-266f-4cba-b93b-08fb65a6595b)

**Comment by cregourd** [comment]
Hi, thanks for your feedback

We've just added these features, the new [v6.1.0](https://www.npmjs.com/package/@premieroctet/next-admin/v/6.1.0) is available, feel free to give another feedback 🚀
