### ISSUE TITLE
[FEATURE] - Increase model depth

### ISSUE THREAD

**Issue by kaluxxx** [premieroctet/next-admin#443]
### Summary

Hello, I would like to display in a Dialog component a model that has more than 3 levels of depth.

Ex: exhibitor.showGuide.address.postalCode or exhibitor.cart.cartItems[1].price

However, the data retrieved from the ClientActionDialogContentProps<T extend ModelName> only contains a maximum of 2 levels of dependencies.

Would it be possible to include a parameter to increase this level of depth?

Thanks in advance! 

### Basic Example

![image](https://github.com/user-attachments/assets/15838a98-aeae-43c4-80c0-4ee1373f418a)

**Comment by cregourd** [comment]
Hi, thanks for your feedback.
A patch is available on [v6.1.6](https://www.npmjs.com/package/@premieroctet/next-admin/v/6.1.6) 🚀

Feel free to give us any other feedback
