### ISSUE TITLE
[FEATURE] - Upgrade package to support Next.js 15

### ISSUE THREAD

**Issue by yasinkocak** [premieroctet/next-admin#479]
### Summary

I would like to request an upgrade to the package to provide full support for Next.js 15. As Next.js is a widely used framework for React applications, having compatibility with this framework would significantly benefit developers working with this package in modern Next.js projects

### Basic Example

Support Nextjs 15

**Comment by foyarash** [comment]
Hello

Can you please elaborate on the issue you are encountering with Next 15 ?

**Comment by cregourd** [comment]
Hi @yasinkocak,

You can now find Next 15 support on [v6.1.8](https://www.npmjs.com/package/@premieroctet/next-admin/v/6.1.8) 🚀
Let us know if you face any issues

**Comment by vincentwinkel** [comment]
Not working for me. Error at runtime:

`Error:  In route /admin/[[...nextadmin]] searchParams are being enumerated. 'searchParams' should be awaited before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis`

(awaiting searchParams is specific to next 15).

My config:
```
    "@premieroctet/next-admin": "^7.1.1",
    "@premieroctet/next-admin-generator-prisma": "^0.0.1",
```
