### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by otamiotto** [premieroctet/next-admin#68]
Is there a way to translate the terms used in the GUI?

**Comment by tlenclos** [comment]
Not at all for now, we should add an i18n system, contribute a few languages and allow users to override the translations.

**Comment by colin27091** [comment]
I18n support is available on [v3.2.0](https://www.npmjs.com/package/@premieroctet/next-admin/v/3.2.0)   🚀
You can now override a list of default translation keys with your favorite i18n tool, you just need to feed Next-Admin with a function that extracts your namespace translation object.
Feel free to give feedback
